'use client'
import { useState } from 'react'
import * as Sentry from '@sentry/nextjs'
import { MessageCircle, X } from 'lucide-react'
import { authenticatedApiFetch } from '@/lib/authenticated-fetch'
import { getApiUrl } from '@/config/api'

export function FeedbackDialog() {
  const [open, setOpen] = useState(false), [kind, setKind] = useState<'bug'|'feature'>('bug'), [description, setDescription] = useState(''), [attempted, setAttempted] = useState(''), [severity, setSeverity] = useState('major'), [screenshot, setScreenshot] = useState<any>(null), [state, setState] = useState<'idle'|'sending'|'sent'|'error'>('idle')
  async function pick(file?: File) { if (!file) return; if (file.size > 5 * 1024 * 1024 || !['image/jpeg','image/png','image/webp'].includes(file.type)) return setState('error'); const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ''; bytes.forEach(byte => binary += String.fromCharCode(byte)); setScreenshot({ name: file.name, content_type: file.type, data: btoa(binary) }); setState('idle') }
  async function submit(e: React.FormEvent) { e.preventDefault(); setState('sending'); try { const r = await authenticatedApiFetch(`${getApiUrl()}/feedback`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind, description, attempted_action: attempted, severity: kind === 'bug' ? severity : undefined, page_url: window.location.href, sentry_event_id: Sentry.lastEventId() || undefined, screenshot }) }); if (!r.ok) throw Error(); setState('sent'); setDescription(''); setAttempted(''); setScreenshot(null) } catch { setState('error') } }
  return <><button type="button" onClick={() => { setOpen(true); setState('idle') }} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/72 hover:bg-white/8 hover:text-white"><MessageCircle size={18}/>Report a problem</button>{open && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/45 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">Help improve Kanvise</h2><p className="mt-1 text-sm text-[#716c76]">Tell us what happened or what you would like us to build.</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Close"><X size={20}/></button></div><div className="mt-5 flex gap-2"><button type="button" onClick={() => setKind('bug')} className={`rounded-full px-3 py-1.5 text-sm ${kind === 'bug' ? 'bg-[#2e2877] text-white' : 'bg-[#f2f0ef]'}`}>Report a problem</button><button type="button" onClick={() => setKind('feature')} className={`rounded-full px-3 py-1.5 text-sm ${kind === 'feature' ? 'bg-[#2e2877] text-white' : 'bg-[#f2f0ef]'}`}>Suggest a feature</button></div>{kind === 'bug' && <select value={severity} onChange={e => setSeverity(e.target.value)} className="mt-4 w-full rounded-lg border p-2"><option value="blocking">Blocking me</option><option value="major">Major</option><option value="minor">Minor</option></select>}<textarea required value={description} onChange={e => setDescription(e.target.value)} maxLength={4000} className="mt-4 min-h-28 w-full rounded-lg border p-3" placeholder={kind === 'bug' ? 'What happened?' : 'What would make Kanvise better?'}/>{kind === 'bug' && <textarea value={attempted} onChange={e => setAttempted(e.target.value)} maxLength={2000} className="mt-3 min-h-20 w-full rounded-lg border p-3" placeholder="What were you trying to do?"/>}<label className="mt-3 block text-sm">Screenshot (optional)<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => void pick(e.target.files?.[0])} className="mt-1 block w-full text-sm"/></label>{screenshot && <p className="mt-1 text-xs">Attached: {screenshot.name}</p>}{state === 'sent' && <p className="mt-3 text-sm text-green-700">Received. We have sent you a confirmation email.</p>}{state === 'error' && <p className="mt-3 text-sm text-red-700">We could not send that report. Please try again.</p>}<button disabled={state === 'sending'} className="mt-5 rounded-lg bg-[#2e2877] px-4 py-2 text-sm font-semibold text-white">{state === 'sending' ? 'Sending…' : 'Send report'}</button></form></div>}</>
}
