'use client'

import { FormEvent, useEffect, useState } from 'react'
import { Copy, Link2 } from 'lucide-react'
import { createBrowserClient } from '@supabase/ssr'
import { toast } from 'sonner'
import { DashboardPageHeader } from '@/components/dashboard/page-header'

type Assignment = { id: string; title: string; description: string; deadline_at: string; revoked_at: string | null; submission_count: number; is_active: boolean }
export default function DirectAssignmentsPage() {
  const [items, setItems] = useState<Assignment[]>([]); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [deadline, setDeadline] = useState(''); const [saving, setSaving] = useState(false)
  const supabase = createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!); const api = process.env.NEXT_PUBLIC_API_URL
  async function request(path: string, options: RequestInit = {}) { const { data } = await supabase.auth.getSession(); return fetch(`${api}${path}`, { ...options, headers: { Authorization: `Bearer ${data.session?.access_token}`, 'Content-Type': 'application/json', ...(options.headers || {}) } }) }
  async function load() { const r = await request('/direct-assignments'); const body = await r.json(); if (r.ok) setItems(body.data || []); else toast.error(body.error || 'Could not load direct assignments') }
  useEffect(() => { void load() }, [])
  async function create(event: FormEvent) { event.preventDefault(); setSaving(true); try { const r = await request('/direct-assignments', { method: 'POST', body: JSON.stringify({ title, description, deadline_at: new Date(deadline).toISOString() }) }); const body = await r.json(); if (!r.ok) throw new Error(body.error); const url = `${window.location.origin}/direct-assignment/${body.share_token}`; await navigator.clipboard.writeText(url); toast.success('Assignment link copied'); setTitle(''); setDescription(''); setDeadline(''); await load() } catch (e) { toast.error(e instanceof Error ? e.message : 'Could not create assignment') } finally { setSaving(false) } }
  return <main className="mx-auto max-w-6xl px-4 py-7 lg:px-8"><DashboardPageHeader title="Direct assignments" description="Send a private assignment link. Learners can submit without creating an account."/><div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-2xl border border-[#e5e1dd] bg-white p-5 shadow-sm sm:p-6"><h2 className="font-bold text-[#180d62]">Create an assignment link</h2><form onSubmit={create} className="mt-5 space-y-4"><label className="block text-sm font-semibold">Title<input required value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 min-h-12 w-full rounded-lg border border-[#8b8580] px-3 font-normal" placeholder="e.g. Algebra practice"/></label><label className="block text-sm font-semibold">Instructions<textarea required value={description} onChange={e=>setDescription(e.target.value)} rows={7} className="mt-2 w-full rounded-lg border border-[#8b8580] p-3 font-normal" placeholder="Write the task your learner should complete…"/></label><label className="block text-sm font-semibold">Deadline<input required type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)} className="mt-2 min-h-12 w-full rounded-lg border border-[#8b8580] px-3 font-normal"/></label><button disabled={saving} className="min-h-12 w-full rounded-xl bg-[#994704] text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Creating…' : 'Create and copy link'}</button></form></section><section className="rounded-2xl border border-[#e5e1dd] bg-white shadow-sm"><div className="border-b border-[#e5e1dd] p-5"><h2 className="font-bold text-[#180d62]">Recent links</h2></div><div className="divide-y divide-[#eeeae6]">{items.length ? items.map(item=><div key={item.id} className="p-5"><div className="flex justify-between gap-3"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-xs text-[#66616c]">Due {new Date(item.deadline_at).toLocaleString()}</p></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.is_active ? 'bg-[#e7f5eb] text-[#196b37]' : 'bg-[#f0eded] text-[#66616c]'}`}>{item.is_active ? 'Active' : 'Closed'}</span></div><p className="mt-3 text-sm text-[#66616c]">{item.submission_count} submission{item.submission_count === 1 ? '' : 's'}</p></div>) : <div className="p-8 text-center text-sm text-[#66616c]"><Link2 className="mx-auto mb-3"/>No direct assignments yet.</div>}</div></section></div></main>
}
