'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { toast } from 'sonner'
import { getApiUrl } from '@/config/api'

export function MockOffersManager({ mockId, token }: { mockId: string; token: string }) {
  const [data, setData] = useState<{ data: any[]; versions: any[] }>({ data: [], versions: [] }); const [loading, setLoading] = useState(true)
  const [slug, setSlug] = useState(''); const [mode, setMode] = useState('free_claim'); const [price, setPrice] = useState(''); const [saving, setSaving] = useState(false)
  async function load() { const response = await fetch(`${getApiUrl()}/mocks/${mockId}/offers`, { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || 'Could not load offers'); setData(body) }
  useEffect(() => { void load().catch(error => toast.error(error.message)).finally(() => setLoading(false)) }, [])
  async function create(event: React.FormEvent) { event.preventDefault(); const version = data.versions[0]; if (!version) { toast.error('Publish this mock before creating a share link'); return }; setSaving(true); try { const response = await fetch(`${getApiUrl()}/mocks/${mockId}/offers`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ mock_exam_version_id: version.id, slug, audience_scope: 'public_link', access_mode: mode, price_kobo: mode === 'paid' ? Math.round(Number(price) * 100) : 0 }) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error || 'Could not create share link'); toast.success('Mock link created'); setSlug(''); setPrice(''); await load() } catch (error) { toast.error(error instanceof Error ? error.message : 'Could not create share link') } finally { setSaving(false) } }
  return <main className="mx-auto max-w-3xl px-4 py-8 pb-24 sm:px-6"><Link href="/dashboard/mocks" className="text-sm font-semibold text-[#2e2877]">← Back to mocks</Link><header className="mt-5"><p className="text-sm font-semibold text-[#994704]">Direct mock access</p><h1 className="mt-1 text-3xl font-semibold">Share & sell this mock</h1><p className="mt-2 text-sm leading-6 text-[#716c76]">Create a private link for this mock. Students can use it without joining a programme or centre.</p></header><form onSubmit={create} className="mt-7 rounded-2xl border border-[#e3ded9] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Link slug<input required value={slug} onChange={e => setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ''))} placeholder="jamb-2026-practice" className="mt-1.5 w-full rounded-lg border border-[#d8d2cc] px-3 py-2" /></label><label className="text-sm font-medium">Access<select value={mode} onChange={e => setMode(e.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d8d2cc] px-3 py-2"><option value="free_claim">Free</option><option value="paid">Paid</option></select></label>{mode === 'paid' && <label className="text-sm font-medium">Price (₦)<input required min="1" type="number" value={price} onChange={e => setPrice(e.target.value)} className="mt-1.5 w-full rounded-lg border border-[#d8d2cc] px-3 py-2" /></label>}</div><button disabled={saving || loading} className="mt-5 rounded-xl bg-[#994704] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving ? 'Creating…' : 'Create link'}</button></form><section className="mt-7 space-y-3">{data.data.map(offer => <article key={offer.id} className="rounded-xl border border-[#e3ded9] bg-white p-4"><p className="font-semibold">{offer.access_mode === 'paid' ? `₦${(offer.price_kobo / 100).toLocaleString()}` : 'Free'} · {offer.is_active ? 'Active' : 'Inactive'}</p><a className="mt-1 block text-sm text-[#2e2877] underline" href={`/mock/${offer.slug}`} target="_blank">/mock/{offer.slug}</a></article>)}{!loading && !data.data.length && <p className="text-sm text-[#716c76]">No share links yet.</p>}</section></main>
}
