'use client'

import Link from 'next/link'
import { useState, type ReactNode } from 'react'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, CalendarDays, ChevronRight, Clock3, Copy, ExternalLink, UsersRound, Video } from 'lucide-react'
import { toast } from 'sonner'
import { authenticatedApiFetch } from '@/lib/authenticated-fetch'

type Session = { id: string; title: string; scheduled_at: string; duration_minutes?: number | null; status: 'scheduled' | 'live' | 'completed' | 'cancelled'; course?: { name?: string | null } | null; courses?: { name?: string | null } | null }
type AttendanceRow = { student_id: string; student_name: string; join_time: string; duration: string; status: 'Present' | 'Late' | 'Absent' }
type Recording = { status: 'pending' | 'transferring' | 'ready' | 'failed'; playback_url?: string | null }
type Tab = 'details' | 'attendance' | 'participants' | 'recording'
const date = new Intl.DateTimeFormat(undefined, { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })
const time = new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' })

export function SessionDetailClient({ sessionId, backHref = '/dashboard/schedule' }: { sessionId: string; backHref?: string }) {
  const api = process.env.NEXT_PUBLIC_API_URL
  const [tab, setTab] = useState<Tab>('details')
  const sessionQuery = useQuery({ queryKey: ['session-detail', sessionId], queryFn: async () => {
    const response = await authenticatedApiFetch(`${api}/live-classes/${sessionId}`); const body = await response.json().catch(() => null)
    if (!response.ok) throw new Error(body?.error || 'Could not load this session'); return body.data as Session
  }})
  const attendanceQuery = useQuery({ queryKey: ['session-attendance', sessionId], enabled: tab === 'attendance' || tab === 'participants', queryFn: async () => {
    const response = await authenticatedApiFetch(`${api}/attendance/records?class_id=${encodeURIComponent(sessionId)}&limit=100`); const body = await response.json().catch(() => null)
    if (!response.ok) throw new Error(body?.error || 'Could not load attendance'); return (body?.data || []) as AttendanceRow[]
  }})
  const recordingQuery = useQuery({ queryKey: ['session-recording', sessionId], enabled: tab === 'recording', queryFn: async () => {
    const response = await authenticatedApiFetch(`${api}/live-classes/${sessionId}/recording`); const body = await response.json().catch(() => null)
    if (response.status === 404) return null; if (!response.ok) throw new Error(body?.error || 'Could not load recording'); return body.data as Recording
  }})
  if (sessionQuery.isPending) return <main className="w-full animate-pulse"><div className="h-4 w-28 rounded bg-[#e9e6e3]"/><div className="mt-6 h-9 w-72 rounded bg-[#e9e6e3]"/><div className="mt-8 h-80 rounded-xl border border-dashboard-outline bg-white"/></main>
  if (!sessionQuery.data) return <main className="w-full"><Link href={backHref} className="inline-flex items-center gap-2 text-sm font-bold text-[#312783]"><ArrowLeft size={16}/>Back to schedule</Link><section className="mt-5 rounded-xl border border-[#f0c7c1] bg-[#fff8f7] p-5 text-sm text-[#8d2f22]">{sessionQuery.error instanceof Error ? sessionQuery.error.message : 'This session could not be loaded.'}</section></main>
  const session = sessionQuery.data; const starts = new Date(session.scheduled_at); const ends = new Date(starts.getTime() + (session.duration_minutes || 0) * 60_000); const subject = session.course?.name || session.courses?.name || 'Private session'; const attendance = attendanceQuery.data || []; const participants = attendance.filter((row) => row.status !== 'Absent')
  return <main className="w-full pb-20 sm:pb-0"><Link href={backHref} className="inline-flex items-center gap-2 text-sm font-bold text-[#625e69] hover:text-[#312783]"><ArrowLeft size={16}/>Back to schedule</Link><header className="mt-4 flex flex-col gap-4 border-b border-dashboard-outline pb-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-xl font-bold tracking-tight text-[#180d62] sm:text-2xl">{subject} — {time.format(starts)}</h1><p className="mt-1 text-sm text-dashboard-muted">{session.title} · {date.format(starts)}</p></div>{session.status !== 'completed' && session.status !== 'cancelled' ? <div className="flex gap-2"><button type="button" onClick={() => void navigator.clipboard.writeText(window.location.origin + "/class/" + session.id).then(() => toast.success('Live class link copied'))} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-[#312783] px-4 text-sm font-bold text-[#312783] hover:bg-[#f1efff]"><Copy size={16}/>Copy link</button><a target="_blank" rel="noopener noreferrer" href={`/class/${session.id}${session.status === 'live' ? '' : '?start=true'}`} className="inline-flex min-h-10 w-fit items-center gap-2 rounded-lg bg-[#312783] px-4 text-sm font-bold text-white">{session.status === 'live' ? 'Join live class' : 'Start live class'}<ExternalLink size={16}/></a></div> : null}</header><nav aria-label="Session detail" className="mt-4 flex gap-5 overflow-x-auto border-b border-dashboard-outline [scrollbar-width:none]">{(['details', 'attendance', 'participants', 'recording'] as const).map((item) => <button type="button" key={item} onClick={() => setTab(item)} className={`shrink-0 border-b-2 py-3 text-sm font-bold capitalize ${tab === item ? 'border-[#994704] text-[#211969]' : 'border-transparent text-[#625e69]'}`}>{item}</button>)}</nav>{tab === 'details' ? <Details session={session} starts={starts} ends={ends} participants={participants.length}/> : null}{tab === 'attendance' ? <AttendanceList rows={attendance} loading={attendanceQuery.isPending} error={attendanceQuery.error instanceof Error ? attendanceQuery.error.message : null} empty="Attendance will appear when this session is completed."/> : null}{tab === 'participants' ? <AttendanceList rows={participants} loading={attendanceQuery.isPending} error={attendanceQuery.error instanceof Error ? attendanceQuery.error.message : null} empty="No learners have joined this session yet." participantsOnly/> : null}{tab === 'recording' ? <RecordingPanel loading={recordingQuery.isPending} error={recordingQuery.error instanceof Error ? recordingQuery.error.message : null} recording={recordingQuery.data || null}/>: null}</main>
}

function Details({ session, starts, ends, participants }: { session: Session; starts: Date; ends: Date; participants: number }) { const classroom = `/class/${session.id}`; const canEnter = session.status === 'scheduled' || session.status === 'live'; return <section className="mt-5 grid max-w-4xl gap-4 md:grid-cols-2"><div className="rounded-xl border border-dashboard-outline bg-white p-5 shadow-dashboard-card"><DetailRow icon={<CalendarDays size={18}/>} label="Date" value={date.format(starts)}/><DetailRow icon={<Clock3 size={18}/>} label="Time" value={`${time.format(starts)} – ${time.format(ends)}${session.duration_minutes ? ` (${session.duration_minutes} min)` : ''}`}/><div className="mt-5 border-t border-dashboard-outline pt-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#625e69]">Live classroom</p><div className="mt-3 flex flex-wrap items-center gap-2">{canEnter ? <a target="_blank" rel="noopener noreferrer" href={`${classroom}${session.status === 'scheduled' ? '?start=true' : ''}`} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-[#312783] px-3.5 text-sm font-bold text-white">{session.status === 'live' ? 'Rejoin session' : 'Start session'}<ExternalLink size={16}/></a> : <span className="text-sm font-semibold text-[#625e69]">This session is {session.status}.</span>}<button type="button" onClick={() => void copyClassroomLink(`${window.location.origin}${classroom}`)} aria-label="Copy classroom link" className="rounded-lg border border-dashboard-outline p-2 text-[#312783]"><Copy size={16}/></button></div></div></div><div className="space-y-4"><DetailCard icon={<UsersRound size={18}/>} label="Participants" value={session.status === 'scheduled' ? 'Available after the session starts' : `${participants} joined`}/><DetailCard icon={<Video size={18}/>} label="Recording" value={session.status === 'scheduled' ? 'Available after the live class ends' : 'See Recording tab'}/><DetailCard icon={<ChevronRight size={18}/>} label="Live session status" value={session.status === 'live' ? 'In progress' : session.status === 'scheduled' ? 'Scheduled' : session.status === 'completed' ? 'Completed' : 'Cancelled'}/></div></section> }
async function copyClassroomLink(value: string) { try { if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(value); else { const input = document.createElement('textarea'); input.value = value; input.style.position = 'fixed'; input.style.opacity = '0'; document.body.appendChild(input); input.select(); const copied = document.execCommand('copy'); input.remove(); if (!copied) throw new Error('Copy was blocked') }; toast.success('Classroom link copied') } catch { toast.error('Could not copy the classroom link') } }
function DetailRow({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="flex gap-3 py-3 first:pt-0"><span className="mt-0.5 text-[#312783]">{icon}</span><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#625e69]">{label}</p><p className="mt-1 text-sm font-semibold text-[#27242d]">{value}</p></div></div> }
function DetailCard({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <article className="rounded-xl border border-dashboard-outline bg-white p-4 shadow-dashboard-card"><div className="flex items-center gap-2 text-[#312783]">{icon}<p className="text-xs font-bold uppercase tracking-[.12em] text-[#625e69]">{label}</p></div><p className="mt-3 text-sm font-bold text-[#27242d]">{value}</p></article> }
function AttendanceList({ rows, loading, error, empty, participantsOnly = false }: { rows: AttendanceRow[]; loading: boolean; error: string | null; empty: string; participantsOnly?: boolean }) { if (loading) return <div className="mt-5 rounded-xl border border-dashboard-outline bg-white p-6 text-sm text-dashboard-muted">Loading…</div>; if (error) return <div className="mt-5 rounded-xl border border-[#f0c7c1] bg-[#fff8f7] p-5 text-sm text-[#8d2f22]">{error}</div>; if (!rows.length) return <div className="mt-5 rounded-xl border border-dashboard-outline bg-white p-8 text-center text-sm text-dashboard-muted">{empty}</div>; return <section className="mt-5 max-w-4xl overflow-hidden rounded-xl border border-dashboard-outline bg-white shadow-dashboard-card"><header className="border-b border-dashboard-outline px-5 py-4"><h2 className="text-base font-bold text-[#180d62]">{participantsOnly ? 'Participants' : 'Attendance'}</h2></header><div className="divide-y divide-dashboard-outline">{rows.map((row) => <article key={row.student_id} className="flex items-center gap-3 px-5 py-4"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#eef0ff] text-xs font-bold text-[#312783]">{row.student_name.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-[#27242d]">{row.student_name}</p><p className="mt-0.5 text-xs text-dashboard-muted">{row.join_time === '--:--' ? 'Did not join' : `Joined ${row.join_time} · ${row.duration}`}</p></div>{!participantsOnly ? <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.status === 'Present' ? 'bg-[#e7f5eb] text-[#14532d]' : row.status === 'Late' ? 'bg-[#fff0e3] text-[#7a3903]' : 'bg-[#f5f3f2] text-[#625e69]'}`}>{row.status}</span> : null}</article>)}</div></section> }
function RecordingPanel({ loading, error, recording }: { loading: boolean; error: string | null; recording: Recording | null }) { if (loading) return <div className="mt-5 rounded-xl border border-dashboard-outline bg-white p-6 text-sm text-dashboard-muted">Checking recording…</div>; if (error) return <div className="mt-5 rounded-xl border border-[#f0c7c1] bg-[#fff8f7] p-5 text-sm text-[#8d2f22]">{error}</div>; if (!recording) return <div className="mt-5 rounded-xl border border-dashboard-outline bg-white p-8 text-center text-sm text-dashboard-muted">No recording is available for this session yet.</div>; return <section className="mt-5 max-w-4xl overflow-hidden rounded-xl border border-dashboard-outline bg-white shadow-dashboard-card"><header className="flex items-center gap-3 border-b border-dashboard-outline px-5 py-4"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-[#eef0ff] text-[#312783]"><Video size={18}/></span><div><h2 className="font-bold text-[#180d62]">Class recording</h2><p className="mt-0.5 text-sm text-dashboard-muted">{recording.status === 'ready' ? 'Ready to watch.' : 'Kanvise is still preparing the recording.'}</p></div></header>{recording.playback_url ? <div className="bg-black"><video controls preload="metadata" className="aspect-video w-full" src={recording.playback_url}>Your browser cannot play this recording. <a href={recording.playback_url}>Open the recording</a>.</video></div> : <div className="p-6 text-sm text-dashboard-muted">The recording is not ready to play yet.</div>}</section> }
